# all packages needed for gsrs_dashboardv7
# run this before running application

install.packages("shiny")
install.packages("shinyWidgets")
install.packages("DT")
install.packages("ggplot2")
install.packages("shinydashboard")
install.packages("tools")
install.packages("httr")
install.packages("gghighlight")
install.packages("dplyr")
install.packages("writexl")
install.packages("plotly")
install.packages("shinyBS")
install.packages("shinycssloaders")
install.packages("formattable")
install.packages("tinytex")
install.packages("dplyr")
install.packages("shinyjs")
install.packages("jsonlite")
install.packages("scales")
install.packages("doBy")
install.packages("readxl")
install.packages("stringr")
install.packages("htmltools")
install.packages("heatmaply")
install.packages("xml2")